/** Scoped portfolio styles use host surfaces and tab-width responsiveness. */
export const triggerStyles = `
.fp-trigger{display:inline-flex;align-self:stretch;align-items:center;justify-content:center;gap:8px;width:36px;height:36px;margin:0;padding:0;border:0;border-radius:50%;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer}.fp-trigger:hover{background:var(--dsw-alias-interactive-bg-hover)}.fp-trigger:focus-visible{outline:2px solid var(--dsw-alias-brand-primary-new-colorprimary-new-color);outline-offset:2px}.fp-trigger>svg{flex:none}.fp-trigger[data-wide=true]{width:100%;height:42px;justify-content:flex-start;padding:0 10px 0 8px;border-radius:12px;text-align:left}.fp-trigger span{min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}
`;
export const styles = `
.fp{--fp-gain:color-mix(in srgb,var(--dsw-alias-state-error-primary) 78%,black);--fp-loss:color-mix(in srgb,var(--dsw-alias-state-success-primary) 60%,black);--fp-estimate:color-mix(in srgb,var(--dsw-alias-link) 78%,black);container-type:inline-size;display:flex;box-sizing:border-box;width:100%;height:100%;min-width:0;min-height:0;flex-direction:column;overflow:hidden;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;line-height:1.5}
body[data-ds-dark-theme] .fp{--fp-gain:var(--dsw-alias-state-error-primary);--fp-loss:var(--dsw-alias-state-success-primary);--fp-estimate:var(--dsw-alias-link)}
.fp h2,.fp h3,.fp p{margin:0}.fp h2{font-size:16px;line-height:24px;font-weight:500;letter-spacing:-.01em}.fp h3{font-size:14px;line-height:22px;font-weight:600}.fp ::selection{background:color-mix(in srgb,var(--dsw-alias-brand-primary-new-colorprimary-new-color) 24%,transparent)}
.fp-sub,.fp-muted{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.fp-sub{margin-top:4px!important;overflow-wrap:anywhere}
.fp-body{display:flex;flex:1;min-height:0;flex-direction:column;gap:20px;overflow:auto;padding:20px 24px 24px;scrollbar-width:thin;scrollbar-color:var(--dsw-alias-border-l3) transparent}.fp-body>*{flex:none}.fp-body::-webkit-scrollbar{width:8px}.fp-body::-webkit-scrollbar-thumb{border:2px solid transparent;border-radius:8px;background:var(--dsw-alias-border-l3);background-clip:padding-box}
.fp-overview{overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1)}.fp-hero{display:flex;flex-direction:column;gap:20px;padding:20px}.fp-total{min-width:0}.fp-total-label{display:flex;align-items:center;flex-wrap:wrap;gap:8px;font-size:13px}.fp-big{display:flex;align-items:baseline;flex-wrap:wrap;gap:8px;margin-top:8px;font-size:32px;line-height:40px;font-weight:600;letter-spacing:-.02em;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.fp-currency{color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:400;letter-spacing:0}.fp-split{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.fp-split>div{min-width:0}.fp-split strong{display:block;margin-top:4px;color:var(--dsw-alias-label-primary);font-size:14px;line-height:22px;font-weight:500;font-variant-numeric:tabular-nums;white-space:normal;overflow-wrap:anywhere}
.fp-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid var(--dsw-alias-border-l2)}.fp-metrics>div{min-width:0;padding:16px 20px}.fp-metrics>div+div{border-left:1px solid var(--dsw-alias-border-l2)}.fp-metrics .fp-muted{display:flex;align-items:center;flex-wrap:wrap;gap:6px}.fp-metrics strong{display:block;margin-top:4px;overflow-wrap:anywhere;font-size:18px;line-height:26px;font-weight:600;font-variant-numeric:tabular-nums;white-space:normal}
.fp-allocation-summary{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:14px 20px;border-top:1px solid var(--dsw-alias-border-l2);background:color-mix(in srgb,var(--dsw-alias-interactive-bg-hover) 28%,transparent)}.fp-allocation-summary>div:first-child{min-width:0}.fp-allocation-summary span,.fp-allocation-summary small{color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.fp-allocation-summary>div:first-child>strong{display:block;margin-top:2px;font-size:13px;line-height:20px}.fp-allocation-summary small{display:block;margin-top:2px}.fp-allocation-totals{display:flex;flex:none;align-items:center;gap:20px;text-align:right}.fp-allocation-totals strong{display:block;color:var(--dsw-alias-label-primary);font-size:14px;font-variant-numeric:tabular-nums}
.fp-content{display:flex;min-width:0;flex-direction:column;gap:20px}.fp-content:focus-visible{outline:2px solid var(--dsw-alias-brand-primary-new-colorprimary-new-color);outline-offset:-2px}.fp-controls{display:flex;min-width:0;flex-direction:column;gap:12px}.fp-line{display:flex;align-items:center;justify-content:space-between;gap:12px}.fp-global-actions,.fp-accountbar{display:flex;align-items:center;justify-content:space-between;gap:8px 20px;min-width:0}.fp-tabs{display:flex;flex:0 1 auto;min-width:0;gap:4px;overflow-x:auto;scrollbar-width:none}.fp-tabs::-webkit-scrollbar{display:none}.fp-secondary-actions,.fp-primary-actions,.fp-account-actions{display:flex;align-items:center;flex-wrap:wrap;gap:8px;min-width:0}.fp-primary-actions,.fp-account-actions{flex:none;margin-left:auto}
.fp-modal-body select{min-width:0;height:32px;padding:0 8px;border:.5px solid var(--dsw-alias-border-l4);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit}.fp-modal-body select:focus{border-color:var(--dsw-alias-brand-primary)}
.fp-list{display:grid;gap:0;overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}.fp-list:empty{display:none}.fp-card{min-width:0;padding:16px 20px 8px}.fp-card+.fp-card{border-top:1px solid var(--dsw-alias-border-l2)}.fp-card:hover{background:color-mix(in srgb,var(--dsw-alias-interactive-bg-hover) 35%,transparent)}.fp-card-main{display:grid;gap:12px;align-items:start}.fp-card-heading{min-width:0}.fp-card-heading h3{overflow-wrap:anywhere}.fp-card-meta{display:flex;align-items:baseline;flex-wrap:wrap;gap:4px 8px}.fp-card-actions{display:flex;flex:none;align-items:center;gap:4px}
.fp-number{font-variant-numeric:tabular-nums;white-space:nowrap}.fp .fp-positive{color:var(--fp-gain)}.fp .fp-negative{color:var(--fp-loss)}.fp-pair{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.fp-pair>div{min-width:0}.fp-pair strong{display:block;margin-top:4px;overflow-wrap:anywhere;white-space:normal;color:var(--dsw-alias-label-primary);font-size:16px;line-height:24px;font-weight:600}.fp-caption{display:block;margin-top:4px;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px;white-space:normal;overflow-wrap:anywhere}
.fp-card-footer{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:start;gap:0 12px;margin-top:8px}.fp-details{grid-column:1/-1;grid-row:1;min-width:0}.fp-card-actions{grid-column:2;grid-row:1}.fp-details-body{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.5fr);gap:8px 16px;margin:8px 0;padding:16px 0 8px;border-top:1px solid var(--dsw-alias-border-l2);font-size:12px;line-height:20px}.fp-details-body dt{color:var(--dsw-alias-label-secondary)}.fp-details-body dd{margin:0;text-align:right;white-space:normal;overflow-wrap:anywhere;font-variant-numeric:tabular-nums}
.fp .fp-quote-note{display:flex;align-items:baseline;gap:8px;margin:12px 0 4px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:20px;overflow-wrap:anywhere}.fp-note-label{flex:none;color:var(--dsw-alias-label-primary)}.fp-quote-note[data-warning=true] .fp-note-label{color:color-mix(in srgb,var(--dsw-alias-state-warn-label) 65%,var(--dsw-alias-label-primary))}
.fp-rebalance{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:12px 0 4px;padding:10px 12px;border-radius:10px;background:color-mix(in srgb,var(--dsw-alias-interactive-bg-hover) 44%,transparent);font-size:12px;line-height:18px}.fp-rebalance-ratio{display:flex;align-items:center;flex-wrap:wrap;gap:5px;color:var(--dsw-alias-label-secondary)}.fp-rebalance-ratio strong{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums}.fp-rebalance-action{flex:none;text-align:right}.fp-rebalance-action strong{display:block}.fp-rebalance-action span,.fp-rebalance>p{margin:0;color:var(--dsw-alias-label-secondary);font-size:11px}.fp-rebalance-action[data-action=buy] strong{color:var(--fp-gain)}.fp-rebalance-action[data-action=sell] strong{color:var(--fp-loss)}
.fp-note{padding:10px 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:19px}.fp-warning{margin:12px 0 0;padding:10px 12px;border-radius:10px;background:color-mix(in srgb,var(--dsw-alias-state-warn-primary) 12%,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-state-warn-label);font-size:12px;line-height:19px}.fp-error{padding:10px 12px;border-radius:10px;background:var(--dsw-alias-state-error-secondary);color:var(--dsw-alias-label-error);font-size:13px;line-height:20px;overflow-wrap:anywhere}
.fp-empty{display:flex;min-height:240px;flex-direction:column;align-items:center;justify-content:center;gap:10px;padding:32px 20px;text-align:center}.fp-empty-icon{display:grid;place-items:center;width:64px;height:64px;margin-bottom:6px;border-radius:16px;background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-secondary)}.fp-empty h3{font-size:15px;line-height:22px;font-weight:500}.fp-empty p{max-width:280px;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:21px}
.fp-modal-body label{display:flex;flex-direction:column;gap:7px;margin:12px 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.fp-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;margin-top:16px}.fp-account{padding:12px 0;border-bottom:1px solid var(--dsw-alias-border-l2)}.fp-account>span{min-width:0;overflow-wrap:anywhere}.fp-account>.fp-line{flex:none;gap:8px}.fp-account:last-of-type{border-bottom:0}.fp-footer{margin-top:4px;padding-top:12px;border-top:1px solid var(--dsw-alias-border-l2)}.fp-footer .fp-note{padding:0 0 4px}
.fp-modal-body{box-sizing:border-box;color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;line-height:1.5}.fp-modal-body p{margin:0}.fp-modal-body h3{margin:0;font-size:14px;line-height:22px;font-weight:600}.fp-account-form{margin-top:16px;padding-top:16px;border-top:1px solid var(--dsw-alias-border-l2)}.fp-modal-body .fp-note{overflow-wrap:anywhere}.fp-filename{margin-top:16px!important;font-weight:600;overflow-wrap:anywhere}.fp-import-summary{display:grid;grid-template-columns:1fr 1fr;gap:16px;padding:16px 0;border-block:1px solid var(--dsw-alias-border-l2)}.fp-import-summary span{color:var(--dsw-alias-label-secondary);font-size:12px}.fp-import-summary strong{display:block;font-size:24px;font-variant-numeric:tabular-nums}.fp-switch-row{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:12px 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}
.fp-allocation-editor{margin-top:8px;border-block:1px solid var(--dsw-alias-border-l2)}.fp-modal-body label.fp-allocation-row{margin:0;padding:12px 0}.fp-allocation-row+.fp-allocation-row{border-top:1px solid var(--dsw-alias-border-l2)}.fp-allocation-row>span:first-child{min-width:0}.fp-allocation-row strong{display:block;overflow-wrap:anywhere;color:var(--dsw-alias-label-primary);font-size:13px;line-height:20px}.fp-allocation-row small{display:block;margin-top:2px;color:var(--dsw-alias-label-secondary);font-size:11px;font-variant-numeric:tabular-nums}.fp-percent-input{display:flex;align-items:center;gap:6px;color:var(--dsw-alias-label-secondary)}.fp-allocation-progress{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:14px 0;border-bottom:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary);font-size:11px}.fp-allocation-progress strong{display:block;margin-top:3px;color:var(--dsw-alias-label-primary);font-size:13px;font-variant-numeric:tabular-nums}
@container(min-width:760px){.fp-hero{flex-direction:row;align-items:center;justify-content:space-between;gap:32px}.fp-split{width:48%;max-width:520px}.fp-card-main{grid-template-columns:minmax(220px,1fr) minmax(0,1.5fr);gap:32px}.fp-pair{text-align:right}.fp-card-footer{margin-top:0}.fp-details-body{grid-template-columns:minmax(0,1fr) minmax(0,2fr);max-width:720px}}
@container(max-width:600px){.fp-body{gap:16px;padding:16px 12px}.fp-content{gap:16px}.fp-global-actions{align-items:stretch;flex-direction:column}.fp-secondary-actions{width:100%;flex-wrap:nowrap;overflow-x:auto;padding-bottom:2px;scrollbar-width:thin}.fp-primary-actions{width:100%;justify-content:flex-end}.fp-accountbar{align-items:center}.fp-account-actions{align-self:stretch}.fp-hero{padding:16px}.fp-metrics>div{padding:12px}.fp-metrics strong{font-size:15px;line-height:22px}.fp-allocation-summary{align-items:flex-start;flex-direction:column;gap:10px;padding:12px 16px}.fp-allocation-totals{width:100%;justify-content:space-between;text-align:left}.fp-card{padding:16px 16px 8px}.fp-pair{gap:12px}.fp-pair strong{font-size:14px;line-height:22px}.fp-rebalance{align-items:flex-start;flex-direction:column;gap:6px}.fp-rebalance-action{text-align:left}}
@container(max-width:380px){.fp-big{font-size:28px}.fp-split{gap:8px}.fp-split strong{font-size:13px}.fp-metrics{grid-template-columns:1fr}.fp-metrics>div{display:flex;align-items:baseline;justify-content:space-between;gap:8px;padding:8px 16px}.fp-metrics>div+div{border-top:1px solid var(--dsw-alias-border-l2);border-left:0}.fp-metrics strong{margin-top:0;text-align:right}.fp-pair{grid-template-columns:repeat(2,minmax(0,1fr))}.fp-pair>div:last-child{grid-column:1/-1;display:flex;align-items:baseline;flex-wrap:wrap;gap:4px 8px}.fp-pair>div:last-child strong{margin:0 0 0 auto}.fp-pair>div:last-child .fp-caption{width:100%;margin-top:0;text-align:right}}
`;
