/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { Account, AccountEdit, AccountInput, AccountRef, BackupFile, EmptyInput, Fund, Holding, HoldingEdit, HoldingInput, HoldingRef, ImportCommit, ImportInput, ImportPreview, LookupInput, MutationResult, Portfolio, PortfolioInput } from 'dsh-fund-portfolio/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$66756e64506f7274666f6c696f {
    accountCreate: (request: AccountInput, signal?: AbortSignal) => Promise<RemoteResult<Account>>
    accountDelete: (request: AccountRef, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    accountList: (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<Account[]>>
    accountUpdate: (request: AccountEdit, signal?: AbortSignal) => Promise<RemoteResult<Account>>
    exportData: (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<BackupFile>>
    holdingAdd: (request: HoldingInput, signal?: AbortSignal) => Promise<RemoteResult<Holding>>
    holdingDelete: (request: HoldingRef, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    holdingList: (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<Holding[]>>
    holdingUpdate: (request: HoldingEdit, signal?: AbortSignal) => Promise<RemoteResult<Holding>>
    importData: (request: ImportCommit, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    lookup: (request: LookupInput, signal?: AbortSignal) => Promise<RemoteResult<Fund>>
    previewImport: (request: ImportInput, signal?: AbortSignal) => Promise<RemoteResult<ImportPreview>>
    summary: (request: PortfolioInput, signal?: AbortSignal) => Promise<RemoteResult<Portfolio>>
  }
  interface TypertRemoteMap {
    'fundPortfolio/accountCreate': (request: AccountInput, signal?: AbortSignal) => Promise<RemoteResult<Account>>
    'fundPortfolio/accountDelete': (request: AccountRef, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    'fundPortfolio/accountList': (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<Account[]>>
    'fundPortfolio/accountUpdate': (request: AccountEdit, signal?: AbortSignal) => Promise<RemoteResult<Account>>
    'fundPortfolio/exportData': (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<BackupFile>>
    'fundPortfolio/holdingAdd': (request: HoldingInput, signal?: AbortSignal) => Promise<RemoteResult<Holding>>
    'fundPortfolio/holdingDelete': (request: HoldingRef, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    'fundPortfolio/holdingList': (_request: EmptyInput, signal?: AbortSignal) => Promise<RemoteResult<Holding[]>>
    'fundPortfolio/holdingUpdate': (request: HoldingEdit, signal?: AbortSignal) => Promise<RemoteResult<Holding>>
    'fundPortfolio/importData': (request: ImportCommit, signal?: AbortSignal) => Promise<RemoteResult<MutationResult>>
    'fundPortfolio/lookup': (request: LookupInput, signal?: AbortSignal) => Promise<RemoteResult<Fund>>
    'fundPortfolio/previewImport': (request: ImportInput, signal?: AbortSignal) => Promise<RemoteResult<ImportPreview>>
    'fundPortfolio/summary': (request: PortfolioInput, signal?: AbortSignal) => Promise<RemoteResult<Portfolio>>
  }
  interface TypertRemoteNamespaceMap {
    'fundPortfolio': TypertRemoteNamespace$66756e64506f7274666f6c696f
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
