/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_fund_portfolio_fundPortfolio_accountCreate_parameter_0$schema = z.object({
  'name': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_accountCreate_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_accountDelete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_accountDelete_result$schema = z.object({
  'ok': z.boolean(),
})
const dsh_fund_portfolio_fundPortfolio_accountList_parameter_0$schema = z.object({
  'unused': z.undefined().readonly().optional(),
})
const dsh_fund_portfolio_fundPortfolio_accountList_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'version': z.number(),
}))
const dsh_fund_portfolio_fundPortfolio_accountUpdate_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'version': z.number(),
  'name': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_accountUpdate_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_exportData_parameter_0$schema = z.object({
  'unused': z.undefined().readonly().optional(),
})
const dsh_fund_portfolio_fundPortfolio_exportData_result$schema = z.object({
  'filename': z.string(),
  'json': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_holdingAdd_parameter_0$schema = z.object({
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_holdingAdd_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_holdingDelete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_holdingDelete_result$schema = z.object({
  'ok': z.boolean(),
})
const dsh_fund_portfolio_fundPortfolio_holdingList_parameter_0$schema = z.object({
  'unused': z.undefined().readonly().optional(),
})
const dsh_fund_portfolio_fundPortfolio_holdingList_result$schema = z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
  'version': z.number(),
}))
const dsh_fund_portfolio_fundPortfolio_holdingUpdate_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'version': z.number(),
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_holdingUpdate_result$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
  'version': z.number(),
})
const dsh_fund_portfolio_fundPortfolio_importData_parameter_0$schema = z.object({
  'json': z.string(),
  'previewToken': z.string(),
  'mode': z.union([z.literal("merge"), z.literal("replace")]),
})
const dsh_fund_portfolio_fundPortfolio_importData_result$schema = z.object({
  'ok': z.boolean(),
})
const dsh_fund_portfolio_fundPortfolio_lookup_parameter_0$schema = z.object({
  'code': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_lookup_result$schema = z.object({
  'code': z.string(),
  'name': z.string(),
  'kind': z.union([z.literal("nav"), z.literal("qdii"), z.literal("money")]),
  'currency': z.literal("CNY"),
  'fetchedAt': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_previewImport_parameter_0$schema = z.object({
  'json': z.string(),
})
const dsh_fund_portfolio_fundPortfolio_previewImport_result$schema = z.object({
  'previewToken': z.string(),
  'accounts': z.number(),
  'holdings': z.number(),
  'conflicts': z.array(z.string()),
})
const dsh_fund_portfolio_fundPortfolio_summary_parameter_0$schema = z.object({
  'accountId': z.union([z.undefined(), z.intersection(z.string(), z.unknown())]).optional(),
  'refresh': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
  'force': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
})
const dsh_fund_portfolio_fundPortfolio_summary_result$schema = z.object({
  'date': z.string(),
  'accounts': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'version': z.number(),
})),
  'holdings': z.array(z.object({
  'holding': z.object({
  'id': z.intersection(z.string(), z.unknown()),
  'accountId': z.intersection(z.string(), z.unknown()),
  'fundCode': z.string(),
  'shares': z.string(),
  'costPrice': z.string(),
  'version': z.number(),
}),
  'accountName': z.string(),
  'fund': z.object({
  'code': z.string(),
  'name': z.string(),
  'kind': z.union([z.literal("nav"), z.literal("qdii"), z.literal("money")]),
  'currency': z.literal("CNY"),
  'fetchedAt': z.string(),
}),
  'quote': z.object({
  'code': z.string(),
  'navs': z.array(z.object({
  'date': z.string(),
  'value': z.string(),
  'annualYield': z.union([z.literal(null), z.string()]),
  'action': z.union([z.literal(null), z.string()]),
})),
  'estimate': z.union([z.literal(null), z.object({
  'date': z.string(),
  'time': z.string(),
  'value': z.string(),
  'referenceValue': z.string(),
  'referenceDate': z.union([z.literal(null), z.string()]),
})]),
  'navFetchedAt': z.union([z.literal(null), z.string()]),
  'estimateFetchedAt': z.union([z.literal(null), z.string()]),
  'error': z.union([z.literal(null), z.string()]),
}),
  'cost': z.string(),
  'marketValue': z.union([z.literal(null), z.string()]),
  'priceKind': z.union([z.literal(null), z.literal("nav"), z.literal("money"), z.literal("estimate")]),
  'priceDate': z.union([z.literal(null), z.string()]),
  'floatingProfit': z.union([z.literal(null), z.string()]),
  'floatingRate': z.union([z.literal(null), z.string()]),
  'confirmed': z.union([z.literal(null), z.object({
  'amount': z.string(),
  'date': z.string(),
  'basisDate': z.union([z.literal(null), z.string()]),
  'kind': z.union([z.literal("confirmed"), z.literal("estimated")]),
})]),
  'estimated': z.union([z.literal(null), z.object({
  'amount': z.string(),
  'date': z.string(),
  'basisDate': z.union([z.literal(null), z.string()]),
  'kind': z.union([z.literal("confirmed"), z.literal("estimated")]),
})]),
  'today': z.union([z.literal(null), z.object({
  'amount': z.string(),
  'date': z.string(),
  'basisDate': z.union([z.literal(null), z.string()]),
  'kind': z.union([z.literal("confirmed"), z.literal("estimated")]),
})]),
  'referenceChange': z.union([z.literal(null), z.string()]),
  'issue': z.union([z.literal(null), z.literal("pending"), z.literal("review"), z.literal("baseline"), z.literal("unavailable")]),
})),
  'cost': z.string(),
  'marketValue': z.union([z.literal(null), z.string()]),
  'marketCovered': z.number(),
  'floatingProfit': z.union([z.literal(null), z.string()]),
  'floatingCovered': z.number(),
  'confirmedToday': z.union([z.literal(null), z.string()]),
  'estimatedToday': z.union([z.literal(null), z.string()]),
  'todayTotal': z.union([z.literal(null), z.string()]),
  'confirmedCount': z.number(),
  'estimatedCount': z.number(),
  'missingCount': z.number(),
  'refreshIntervalMs': z.number(),
})

export const TYPERT = {
  package: 'dsh-fund-portfolio',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-fund-portfolio#fundPortfolio/accountCreate',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'accountCreate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#AccountInput',
            schema: dsh_fund_portfolio_fundPortfolio_accountCreate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Account',
        schema: dsh_fund_portfolio_fundPortfolio_accountCreate_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":69,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/accountDelete',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'accountDelete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#AccountRef',
            schema: dsh_fund_portfolio_fundPortfolio_accountDelete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#MutationResult',
        schema: dsh_fund_portfolio_fundPortfolio_accountDelete_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":81,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/accountList',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'accountList',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#EmptyInput',
            schema: dsh_fund_portfolio_fundPortfolio_accountList_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio#fundPortfolio/accountList:result',
        schema: dsh_fund_portfolio_fundPortfolio_accountList_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":63,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/accountUpdate',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'accountUpdate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#AccountEdit',
            schema: dsh_fund_portfolio_fundPortfolio_accountUpdate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Account',
        schema: dsh_fund_portfolio_fundPortfolio_accountUpdate_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":75,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/exportData',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'exportData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#EmptyInput',
            schema: dsh_fund_portfolio_fundPortfolio_exportData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#BackupFile',
        schema: dsh_fund_portfolio_fundPortfolio_exportData_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":150,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/holdingAdd',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'holdingAdd',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#HoldingInput',
            schema: dsh_fund_portfolio_fundPortfolio_holdingAdd_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Holding',
        schema: dsh_fund_portfolio_fundPortfolio_holdingAdd_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":102,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/holdingDelete',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'holdingDelete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#HoldingRef',
            schema: dsh_fund_portfolio_fundPortfolio_holdingDelete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#MutationResult',
        schema: dsh_fund_portfolio_fundPortfolio_holdingDelete_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":114,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/holdingList',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'holdingList',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#EmptyInput',
            schema: dsh_fund_portfolio_fundPortfolio_holdingList_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio#fundPortfolio/holdingList:result',
        schema: dsh_fund_portfolio_fundPortfolio_holdingList_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":96,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/holdingUpdate',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'holdingUpdate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#HoldingEdit',
            schema: dsh_fund_portfolio_fundPortfolio_holdingUpdate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Holding',
        schema: dsh_fund_portfolio_fundPortfolio_holdingUpdate_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":108,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/importData',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'importData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#ImportCommit',
            schema: dsh_fund_portfolio_fundPortfolio_importData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#MutationResult',
        schema: dsh_fund_portfolio_fundPortfolio_importData_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":165,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/lookup',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'lookup',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#LookupInput',
            schema: dsh_fund_portfolio_fundPortfolio_lookup_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Fund',
        schema: dsh_fund_portfolio_fundPortfolio_lookup_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":90,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/previewImport',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'previewImport',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#ImportInput',
            schema: dsh_fund_portfolio_fundPortfolio_previewImport_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#ImportPreview',
        schema: dsh_fund_portfolio_fundPortfolio_previewImport_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":159,"column":9},
    },
    {
      id: 'dsh-fund-portfolio#fundPortfolio/summary',
      service: 'fundPortfolio',
      namespace: 'fundPortfolio',
      method: 'summary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-fund-portfolio/types#PortfolioInput',
            schema: dsh_fund_portfolio_fundPortfolio_summary_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-fund-portfolio/types#Portfolio',
        schema: dsh_fund_portfolio_fundPortfolio_summary_result$schema,
      },
      sourceLocation: {"file":"packages/portfolio/src/index.ts","line":123,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "fundPortfolio",
        "exportName": "FundPortfolioService",
        "members": [
          {
            "kind": "method",
            "name": "accountList",
            "signature": "@Remote async accountList(_request: EmptyInput, signal: AbortSignal): Promise<Account[]>",
            "summary": "List all accounts.",
            "jsDoc": "/** List all accounts. @param _request Empty request. @param signal Cancellation. @returns Current accounts. */"
          },
          {
            "kind": "method",
            "name": "accountCreate",
            "signature": "@Remote async accountCreate(request: AccountInput, signal: AbortSignal): Promise<Account>",
            "summary": "Create an account.",
            "jsDoc": "/** Create an account. @param request Account name. @param signal Cancellation. @returns Persisted account. */"
          },
          {
            "kind": "method",
            "name": "accountUpdate",
            "signature": "@Remote async accountUpdate(request: AccountEdit, signal: AbortSignal): Promise<Account>",
            "summary": "Rename with optimistic concurrency.",
            "jsDoc": "/** Rename with optimistic concurrency. @param request Expected version and name. @param signal Cancellation. @returns Updated account. */"
          },
          {
            "kind": "method",
            "name": "accountDelete",
            "signature": "@Remote async accountDelete(request: AccountRef, signal: AbortSignal): Promise<MutationResult>",
            "summary": "Delete an empty account.",
            "jsDoc": "/** Delete an empty account. @param request Expected account version. @param signal Cancellation. @returns Successful deletion. */"
          },
          {
            "kind": "method",
            "name": "lookup",
            "signature": "@Remote async lookup(request: LookupInput, signal: AbortSignal): Promise<Fund>",
            "summary": "Verify a fund code with the public provider.",
            "jsDoc": "/** Verify a fund code with the public provider. @param request Six-digit fund code. @param signal Cancellation. @returns Verified metadata. */"
          },
          {
            "kind": "method",
            "name": "holdingList",
            "signature": "@Remote async holdingList(_request: EmptyInput, signal: AbortSignal): Promise<Holding[]>",
            "summary": "List current holdings without refreshing market data.",
            "jsDoc": "/** List current holdings without refreshing market data. @param _request Empty request. @param signal Cancellation. @returns Holdings and record versions. */"
          },
          {
            "kind": "method",
            "name": "holdingAdd",
            "signature": "@Remote async holdingAdd(request: HoldingInput, signal: AbortSignal): Promise<Holding>",
            "summary": "Add a previously verified fund.",
            "jsDoc": "/** Add a previously verified fund. @param request Account, fund and decimal values. @param signal Cancellation. @returns Persisted holding. */"
          },
          {
            "kind": "method",
            "name": "holdingUpdate",
            "signature": "@Remote async holdingUpdate(request: HoldingEdit, signal: AbortSignal): Promise<Holding>",
            "summary": "Edit with optimistic concurrency.",
            "jsDoc": "/** Edit with optimistic concurrency. @param request Expected version and replacement values. @param signal Cancellation. @returns Updated holding. */"
          },
          {
            "kind": "method",
            "name": "holdingDelete",
            "signature": "@Remote async holdingDelete(request: HoldingRef, signal: AbortSignal): Promise<MutationResult>",
            "summary": "Delete a holding.",
            "jsDoc": "/** Delete a holding. @param request Expected holding version. @param signal Cancellation. @returns Successful deletion. */"
          },
          {
            "kind": "method",
            "name": "summary",
            "signature": "@Remote async summary(request: PortfolioInput, signal: AbortSignal): Promise<Portfolio>",
            "summary": "Calculate current-share returns, optionally refreshing quotes.",
            "jsDoc": "/** Calculate current-share returns, optionally refreshing quotes. @param request Account filter and refresh policy. @param signal Cancellation. @returns Dated results including coverage and missing values. */"
          },
          {
            "kind": "method",
            "name": "exportData",
            "signature": "@Remote async exportData(_request: EmptyInput, signal: AbortSignal): Promise<BackupFile>",
            "summary": "Export private portfolio data, without market caches.",
            "jsDoc": "/** Export private portfolio data, without market caches. @param _request Empty request. @param signal Cancellation. @returns JSON backup and suggested filename. */"
          },
          {
            "kind": "method",
            "name": "previewImport",
            "signature": "@Remote async previewImport(request: ImportInput, signal: AbortSignal): Promise<ImportPreview>",
            "summary": "Preview an import without mutation.",
            "jsDoc": "/** Preview an import without mutation. @param request Backup JSON. @param signal Cancellation. @returns Conflict list and state-bound token. */"
          },
          {
            "kind": "method",
            "name": "importData",
            "signature": "@Remote async importData(request: ImportCommit, signal: AbortSignal): Promise<MutationResult>",
            "summary": "Apply an explicitly confirmed preview in one transaction.",
            "jsDoc": "/** Apply an explicitly confirmed preview in one transaction. @param request Backup, mode and preview token. @param signal Cancellation. @returns Successful import. */"
          }
        ],
        "types": [
          {
            "name": "Account",
            "declaration": "export interface Account {\n    id: AccountId;\n    name: string;\n    version: number;\n}"
          },
          {
            "name": "AccountEdit",
            "declaration": "export interface AccountEdit {\n    id: AccountId;\n    version: number;\n    name: string;\n}"
          },
          {
            "name": "AccountId",
            "declaration": "export type AccountId = Branded<'FundAccountId'>;"
          },
          {
            "name": "AccountInput",
            "declaration": "export interface AccountInput {\n    name: string;\n}"
          },
          {
            "name": "AccountRef",
            "declaration": "export interface AccountRef {\n    id: AccountId;\n    version: number;\n}"
          },
          {
            "name": "BackupFile",
            "declaration": "export interface BackupFile {\n    filename: string;\n    json: string;\n}"
          },
          {
            "name": "EmptyInput",
            "declaration": "export interface EmptyInput {\n    readonly unused?: never;\n}"
          },
          {
            "name": "Estimate",
            "declaration": "export interface Estimate {\n    date: string;\n    time: string;\n    value: string;\n    referenceValue: string;\n    referenceDate: string | null;\n}"
          },
          {
            "name": "Fund",
            "declaration": "export interface Fund {\n    code: string;\n    name: string;\n    kind: FundKind;\n    currency: 'CNY';\n    fetchedAt: string;\n}"
          },
          {
            "name": "FundKind",
            "declaration": "export type FundKind = 'nav' | 'qdii' | 'money';"
          },
          {
            "name": "Holding",
            "declaration": "export interface Holding {\n    id: HoldingId;\n    accountId: AccountId;\n    fundCode: string;\n    shares: string;\n    costPrice: string;\n    version: number;\n}"
          },
          {
            "name": "HoldingEdit",
            "declaration": "export interface HoldingEdit extends HoldingInput {\n    id: HoldingId;\n    version: number;\n}"
          },
          {
            "name": "HoldingId",
            "declaration": "export type HoldingId = Branded<'FundHoldingId'>;"
          },
          {
            "name": "HoldingInput",
            "declaration": "export interface HoldingInput {\n    accountId: AccountId;\n    fundCode: string;\n    shares: string;\n    costPrice: string;\n}"
          },
          {
            "name": "HoldingRef",
            "declaration": "export interface HoldingRef {\n    id: HoldingId;\n    version: number;\n}"
          },
          {
            "name": "HoldingView",
            "declaration": "export interface HoldingView {\n    holding: Holding;\n    accountName: string;\n    fund: Fund;\n    quote: Quote;\n    cost: string;\n    marketValue: string | null;\n    priceKind: 'nav' | 'estimate' | 'money' | null;\n    priceDate: string | null;\n    floatingProfit: string | null;\n    floatingRate: string | null;\n    confirmed: Income | null;\n    estimated: Income | null;\n    today: Income | null;\n    referenceChange: string | null;\n    issue: 'pending' | 'review' | 'baseline' | 'unavailable' | null;\n}"
          },
          {
            "name": "ImportCommit",
            "declaration": "export interface ImportCommit {\n    json: string;\n    previewToken: string;\n    mode: 'merge' | 'replace';\n}"
          },
          {
            "name": "ImportInput",
            "declaration": "export interface ImportInput {\n    json: string;\n}"
          },
          {
            "name": "ImportPreview",
            "declaration": "export interface ImportPreview {\n    previewToken: string;\n    accounts: number;\n    holdings: number;\n    conflicts: string[];\n}"
          },
          {
            "name": "Income",
            "declaration": "export interface Income {\n    amount: string;\n    date: string;\n    basisDate: string | null;\n    kind: 'confirmed' | 'estimated';\n}"
          },
          {
            "name": "LookupInput",
            "declaration": "export interface LookupInput {\n    code: string;\n}"
          },
          {
            "name": "MutationResult",
            "declaration": "export interface MutationResult {\n    ok: boolean;\n}"
          },
          {
            "name": "Nav",
            "declaration": "export interface Nav {\n    date: string;\n    value: string;\n    annualYield: string | null;\n    action: string | null;\n}"
          },
          {
            "name": "Portfolio",
            "declaration": "export interface Portfolio {\n    date: string;\n    accounts: Account[];\n    holdings: HoldingView[];\n    cost: string;\n    marketValue: string | null;\n    marketCovered: number;\n    floatingProfit: string | null;\n    floatingCovered: number;\n    confirmedToday: string | null;\n    estimatedToday: string | null;\n    todayTotal: string | null;\n    confirmedCount: number;\n    estimatedCount: number;\n    missingCount: number;\n    refreshIntervalMs: number;\n}"
          },
          {
            "name": "PortfolioInput",
            "declaration": "export interface PortfolioInput {\n    accountId?: AccountId;\n    refresh?: boolean;\n    force?: boolean;\n}"
          },
          {
            "name": "Quote",
            "declaration": "export interface Quote {\n    code: string;\n    navs: Nav[];\n    estimate: Estimate | null;\n    navFetchedAt: string | null;\n    estimateFetchedAt: string | null;\n    error: string | null;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
