/** Scoped portfolio styles use host surfaces and tab-width responsiveness. */
export const styles = `
.fp{container-type:inline-size;height:100%;overflow:auto;padding:24px;color:inherit;background:var(--dsw-specific-sidebar-fill,transparent);font:inherit}
.fp *{box-sizing:border-box}.fp h2,.fp h3,.fp p{margin:0}.fp h2{font-size:21px;font-weight:650;letter-spacing:-.5px}.fp h3{font-size:15px;font-weight:600}
.fp-header,.fp-toolbar,.fp-line{display:flex;align-items:center;justify-content:space-between;gap:12px}.fp-header{margin-bottom:24px}.fp-sub,.fp-muted{opacity:.65;font-size:12px;line-height:1.6}.fp-sub{margin-top:4px!important}
.fp button,.fp select,.fp input,.fp textarea{font:inherit;color:inherit}.fp button,.fp select{min-height:34px;border:1px solid color-mix(in srgb,currentColor 15%,transparent);border-radius:7px;background:transparent;padding:6px 10px;cursor:pointer}
.fp button:hover{background:color-mix(in srgb,currentColor 6%,transparent)}.fp button:disabled{opacity:.45;cursor:default}.fp button:focus-visible,.fp input:focus-visible,.fp textarea:focus-visible,.fp select:focus-visible{outline:2px solid #658cff;outline-offset:2px}
.fp button.fp-primary{background:#315ccf;color:white;border-color:transparent}.fp button.fp-danger{background:#b32c40;color:white;border-color:transparent}
.fp-hero{padding:22px;border-radius:12px;background:var(--dsw-specific-bubble,color-mix(in srgb,currentColor 5%,transparent));margin-bottom:20px}
.fp-big{font-size:36px;letter-spacing:-1px;font-weight:650;font-variant-numeric:tabular-nums;line-height:1.3;margin:7px 0 14px}
.fp-split{display:flex;flex-wrap:wrap;gap:12px 22px;font-size:12px}.fp-split strong{display:block;font-size:15px;font-weight:550;font-variant-numeric:tabular-nums;margin-top:4px}
.fp-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:0 0 26px}.fp-metrics strong{display:block;font-size:17px;font-weight:600;margin:6px 0;font-variant-numeric:tabular-nums}
.fp-toolbar{flex-wrap:wrap;margin-bottom:18px}.fp-toolbar>div{display:flex;gap:8px;flex-wrap:wrap}.fp-list{display:grid;gap:14px}.fp-card{border:1px solid color-mix(in srgb,currentColor 12%,transparent);border-radius:10px;padding:16px}.fp-card header{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}
.fp-number{font-variant-numeric:tabular-nums;white-space:nowrap}.fp-positive{color:#c84142}.fp-negative{color:#168360}.fp-pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.fp-pair strong{display:block;font-weight:550;margin-top:4px}.fp-details{border-top:1px solid color-mix(in srgb,currentColor 10%,transparent);margin-top:14px;padding-top:12px}.fp-details summary{cursor:pointer;font-size:12px;opacity:.7}.fp-details dl{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px}.fp-details dt{opacity:.65}.fp-details dd{margin:0;text-align:right;overflow-wrap:anywhere}
.fp-note{font-size:12px;line-height:1.6;padding:12px 0;opacity:.7}.fp-warning{font-size:12px;padding:10px 12px;border-radius:7px;background:color-mix(in srgb,#df9d26 12%,transparent);line-height:1.5;margin:12px 0}.fp-error{font-size:12px;padding:12px;background:color-mix(in srgb,#cc4050 10%,transparent);border-radius:7px;overflow-wrap:anywhere;margin-bottom:12px}
.fp-empty{padding:45px 15px;text-align:center}.fp-empty p{margin-top:10px;line-height:1.7;opacity:.65;font-size:13px}.fp-form{padding:18px;border:1px solid color-mix(in srgb,currentColor 15%,transparent);border-radius:10px;margin-bottom:18px}.fp-form label{display:block;font-size:12px;margin:12px 0 6px}.fp-form input,.fp-form select,.fp-form textarea{width:100%;padding:9px 10px;border:1px solid color-mix(in srgb,currentColor 20%,transparent);border-radius:6px;background:transparent;min-width:0}.fp-form textarea{min-height:150px;resize:vertical;font-family:monospace;font-size:12px}.fp-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}.fp-account{padding:10px 0;border-bottom:1px solid color-mix(in srgb,currentColor 10%,transparent)}
.fp-trigger{display:flex;align-items:center;justify-content:center;gap:8px;min-height:36px;border:0;background:transparent;color:inherit;cursor:pointer;font:inherit}
@container(max-width:440px){.fp-metrics{grid-template-columns:1fr;gap:10px}.fp-metrics>div{display:flex;align-items:baseline;justify-content:space-between;gap:10px}.fp-header{align-items:flex-start}.fp-big{font-size:30px}.fp-pair{gap:10px}.fp-card{padding:13px}}
@media(prefers-color-scheme:dark){.fp-positive{color:#f17e80}.fp-negative{color:#64c99b}}
`
